version: "3.8"

networks:
  full-application:
    driver: bridge

services:
  database: 
    image: postgres
    networks:
      - full-application
    container_name: postgres-container
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=default_db
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /home/node/app
    networks:
      - full-application
    container_name: node-container
    restart: always
    env_file: ./backend/.env
    depends_on:
      - database
    environment:
      - POSTGRES_DATABASE=default_db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    ports:
      - "3003:3000"
  web: 
    build: ./frontend
    working_dir: /usr/app
    container_name: react-container
    networks:
      - full-application
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
