version: "3.8"

services:
  db: 
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "3003:3000"
  web: 
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
