version: "3.8"

services:
  db: 
    image: postgres
    restart: always
    container_name: postgres-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-container
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      POSTGRES_USER: myname
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: docker
    ports:
      - "3003:3000"
  web: 
    build: ./frontend
    container_name: react-container
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
    external: true