version: '3.8'

networks:
  development-network:
    driver: bridge

services:
  db: 
    image: postgres
    restart: always
    networks:
      - development-network
    environment:  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 80s
  api: 
    build: ./backend
    networks:
      - development-network
    env_file: ./backend/.env
    environment:  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:3000"
  react: 
    build: ./frontend
    networks:
      - development-network
    depends_on:
      - api
    ports:
      - "3000:3000"